from pathlib import Path
root=Path(__file__).resolve().parents[1]
def write(p,s): (root/p).write_text(s,encoding='utf-8')
write('src/data/experience.ts', '''export const experience = [
 {company:'HiveTech AI',role:'Prototyping & Development Intern',period:'May 2026–Present',description:'Developing and testing connected sensing hardware, bringing together physical prototyping, device integration, and experimental analysis.',contributions:[
 'Contribute to hardware prototyping and development, including CAD work for heatsink and microcontroller assemblies.',
 'Conduct indoor and outdoor Wi-Fi field tests to evaluate upload behavior, distance, obstructions, and connection reliability.',
 'Analyze camera and sensor logs, distinguishing thermal sleep from network disconnections and active transfer rate from connection availability.',
 'Measure current draw and power consumption across subsystem configurations to support power budgeting and thermal evaluation.',
 'Prepare technical reports documenting test methods, findings, limitations, and follow-up experiments.'
 ],skills:['Prototyping','Hardware development','Field testing','Data analysis']},
 {company:'Diagnostic Devices Inc. (DDI)',role:'R&D Deployment Engineer · internship',period:'Aug 2024–Feb 2025',description:'Technical deployment and troubleshooting support for eCAD, a non-invasive cardiovascular detection device.',contributions:[
 'Assisted with device deployment and investigated hardware and software issues using programming and system analysis.',
 'Collaborated with the engineering team to diagnose technical problems and support improvements to device performance.'
 ],skills:['System troubleshooting','Programming','Hardware integration']},
 {company:'University of Hartford Makerspace',role:'Makerspace Monitor',period:'Aug 2023–Apr 2025',description:'Fabrication support and practical instruction for students turning designs into physical parts.',contributions:[
 'Supported 3D printing, laser cutting, and CNC machining operations, including equipment setup and maintenance.',
 'Guided students through fabrication processes and provided training on tools and equipment.'
 ],skills:['Digital fabrication','Equipment maintenance','Student training']}
];
export const skillGroups = [
 {title:'Programming & analysis',items:'Python, C++ / Arduino, MATLAB, LabVIEW, Excel, signal processing and Fourier analysis.'},
 {title:'Electronics & integration',items:'Microcontrollers, sensor logging, circuit and PCB prototyping, soldering, power measurements, hardware/software troubleshooting.'},
 {title:'Design & fabrication',items:'SolidWorks, AutoCAD, Revit, 3D printing, laser cutting, CNC machining, mechanical prototyping.'},
 {title:'Testing & collaboration',items:'Bench and field experiments, technical documentation, data interpretation, project coordination, procurement, and student instruction.'}
];
''')
write('src/pages/about.astro','''---
import BaseLayout from '../layouts/BaseLayout.astro';
import {experience} from '../data/experience';
---
<BaseLayout title="About | Kiden Scruton" description="Kiden Scruton: an aerospace engineering background with experience in hardware development, testing, fabrication, and team leadership.">
 <header class="page-header"><p class="eyebrow">About me</p><h1>I like making ideas work in the real world.</h1><p class="intro">My background is in aerospace engineering at the University of Hartford. My work brings together programming, electronics, mechanical design, and the hands-on process of building and testing.</p></header>
 <div class="about-intro"><article class="prose"><h2>From an idea to a working system</h2><p>I’m drawn to projects where software interacts with something physical: a sensor, a mechanism, a wearable display, or a payload. I enjoy moving between the model, the code, and the workbench to understand how those pieces behave together.</p><p>That has taken me from programming a hazard-sensing robot and an Expo-winning wearable headset to investigating vibration data for RockSat-C. Each project has required a different combination of analysis, fabrication, troubleshooting, and teamwork.</p><p>My approach is practical: build something testable, observe what happens, and use the evidence to decide what to change. A useful result can be a working prototype or a clear explanation of why a design needs another iteration.</p></article><aside class="about-focus"><p class="eyebrow">What I bring</p><h2>Build. Measure. Understand.</h2><ul><li>Software connected to real hardware</li><li>Careful testing and data interpretation</li><li>Fabrication and hands-on troubleshooting</li><li>Clear documentation and shared problem-solving</li></ul><a class="text-link" href="/projects/">Explore the project work ↗</a></aside></div>
 <section class="section-block" aria-labelledby="experience-title"><div class="section-top"><div><p class="eyebrow">Experience in practice</p><h2 id="experience-title">Across the lab and the workbench.</h2></div></div><div class="about-experience">{experience.map(item=><article><p class="eyebrow">{item.company}</p><h3>{item.role}</h3><p>{item.description}</p>{item.company==='HiveTech AI' && <p>Since May 2026, my work has included prototyping and development alongside Wi-Fi field experiments, power measurements, and technical reporting. Testing helps me connect a design decision with how the hardware actually behaves.</p>}</article>)}</div></section>
 <section class="about-intro section-block" aria-labelledby="leadership-title"><article class="prose"><p class="eyebrow">Working with people</p><h2 id="leadership-title">Taking responsibility beyond my own part.</h2><p>As a RockSat-C co-lead, I helped coordinate technical work, timelines, procurement, and budgets alongside payload development. The 2025 mission completed launch, recovery, and data collection, and I was part of the launch team.</p><p>I also served as founding president of the University of Hartford Kappa Sigma chapter. Building a new organization meant developing recruitment and organizational processes, leading events, and supporting philanthropic initiatives.</p><p>Before university, I co-founded Scruton Brothers Ice Cream, an allergy-friendly business in Southern Pines, North Carolina. Equipment problems and supply logistics gave me early experience with solving practical problems while keeping an operation running.</p></article><aside class="about-focus"><p class="eyebrow">Away from the desk</p><h2>Still making things.</h2><p>I enjoy model rocketry and airplane building, DIY electronics, custom computers, welding, and automotive maintenance. Outside the workshop, my interests include hiking, off-roading, and golf.</p><p>Those interests share something with my engineering work: curiosity about how things behave, and the patience to learn by doing.</p></aside></section>
 <div class="profile-cta"><div><h2>A closer look at my experience</h2><p>Roles, technical skills, selected projects, and recognition.</p></div><a class="button primary" href="/resume/">View my resume →</a></div>
</BaseLayout>
''')
write('src/pages/resume.astro','''---
import BaseLayout from '../layouts/BaseLayout.astro';
import {experience,skillGroups} from '../data/experience';
---
<BaseLayout title="Resume | Kiden Scruton" description="Kiden Scruton's experience at HiveTech AI, Diagnostic Devices Inc., and the University of Hartford Makerspace, plus engineering projects and leadership.">
 <header class="page-header"><p class="eyebrow">Resume</p><h1>Experience & qualifications</h1><p class="intro">Aerospace engineering background with practical experience in hardware development, device testing, embedded programming, and fabrication.</p><div class="resume-contact"><a href="mailto:scrutonkiden@gmail.com">scrutonkiden@gmail.com ↗</a><a href="https://www.linkedin.com/in/Kiden-Scruton/">LinkedIn ↗</a><button type="button" class="print-resume">Print / save as PDF ↓</button></div></header>
 <div class="resume-layout"><nav class="resume-nav" aria-label="Resume sections"><a href="#experience">Experience</a><a href="#education">Education</a><a href="#projects">Selected projects</a><a href="#skills">Technical skills</a><a href="#leadership">Leadership</a><a href="#recognition">Recognition</a></nav><div class="resume-content">
 <section id="experience" class="resume-section"><p class="eyebrow">01 / Experience</p><h2>Engineering & fabrication</h2>{experience.map(item=><article class="experience-entry"><div class="entry-heading"><div><h3>{item.company}</h3><p class="entry-role">{item.role}</p></div><p class="entry-date">{item.period}</p></div><p>{item.description}</p><ul>{item.contributions.map(point=><li>{point}</li>)}</ul><div class="skill-tags">{item.skills.map(skill=><span>{skill}</span>)}</div></article>)}</section>
 <section id="education" class="resume-section"><p class="eyebrow">02 / Education</p><h2>University of Hartford</h2><p class="entry-role">Aerospace engineering studies</p><p>Project work spanning embedded systems, engineering design, mechatronics, controls, and payload development. Activities include AIAA, RockSat-C, and founding involvement in AURORA, the Advanced Undergraduate Rocketry Operations and Research Association.</p></section>
 <section id="projects" class="resume-section"><p class="eyebrow">03 / Selected projects</p><h2>Engineering in practice</h2><article class="resume-project"><h3><a href="/projects/rocksat-c/">RockSat-C payload development ↗</a></h3><p class="entry-role">Co-lead · vibration subsystem</p><p>Applied Fourier analysis to accelerometer records, developed transducer assembly concepts, and contributed to payload prototyping and integration. Helped coordinate team tasks and budgets; participated in the 2025 launch team.</p></article><article class="resume-project"><h3><a href="/projects/arsh/">ARSH wearable sensing headset ↗</a></h3><p class="entry-role">Programming & procurement lead</p><p>Developed the Python-based QR scanning and display workflow on Raspberry Pi hardware, shared hardware development, and supported the team’s wearable IoT demonstration.</p></article><article class="resume-project"><h3><a href="/projects/hazard-sensing-robot/">Hazard Sensing Robot ↗</a></h3><p class="entry-role">Programming & hardware integration</p><p>Developed the XIAO sensor-logging program and an early proof of concept, then helped integrate sensing, onboard storage, and the physical robot.</p></article><article class="resume-project"><h3><a href="/projects/brennan-gyro-monorail/">Gyroscopic monorail prototype ↗</a></h3><p class="entry-role">Modeling & prototyping</p><p>Connected dynamic modeling and LabVIEW control simulation with CAD and a physical flywheel prototype. Identified flywheel mass and motor-speed control as key limitations.</p></article></section>
 <section id="skills" class="resume-section"><p class="eyebrow">04 / Technical skills</p><h2>Tools & methods</h2><div class="resume-skills">{skillGroups.map(group=><div><h3>{group.title}</h3><p>{group.items}</p></div>)}</div></section>
 <section id="leadership" class="resume-section"><p class="eyebrow">05 / Leadership</p><h2>Organizations & entrepreneurship</h2><article class="resume-project"><div class="entry-heading"><h3>Kappa Sigma · University of Hartford</h3><p class="entry-date">Dec 2023–Dec 2024</p></div><p class="entry-role">Founding President</p><p>Established the chapter and developed recruitment and organizational processes. Led events and philanthropic initiatives as the organization grew.</p></article><article class="resume-project"><div class="entry-heading"><h3>Scruton Brothers Ice Cream</h3><p class="entry-date">Jan 2021–Jan 2023</p></div><p class="entry-role">Co-Founder · Southern Pines, NC</p><p>Co-founded an allergy-friendly business and worked through equipment and supply-chain challenges, developing practical operations, communication, and leadership skills.</p></article></section>
 <section id="recognition" class="resume-section"><p class="eyebrow">06 / Recognition</p><h2>Selected team achievements</h2><ul><li><strong>ARSH, Spring 2024:</strong> winner of the HSB-sponsored Expo section; separately listed as a sophomore honorable mention in the <a href="https://www.hartford.edu/news/press-releases/2024/05/ns-spring-ceta-expo-recap.aspx">university recap</a>.</li><li><strong>Hazard Sensing Robot, 2022:</strong> tied first place at the CETA Expo, as recorded in the team report; named among the <a href="https://www.hartford.edu/unotes/2022/12/ceta-design-expo-features-student-inventions.aspx">university’s winning projects</a>.</li></ul></section>
 </div></div>
 <div class="profile-cta"><div><h2>Let’s talk about your project.</h2><p>For more about my approach and interests, visit <a href="/about/">About me</a>.</p></div><a class="button primary" href="mailto:scrutonkiden@gmail.com">Get in touch ↗</a></div>
</BaseLayout>
<script>document.querySelector('.print-resume')?.addEventListener('click',()=>window.print());</script>
''')
print('Expanded About and Resume with shared experience data.')
