from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(file,old,new):
 p=root/file;s=p.read_text(encoding='utf-8');assert old in s,(file,old);p.write_text(s.replace(old,new),encoding='utf-8')
edit('src/pages/resume.astro','fall 2025','January 2026')
edit('src/pages/resume.astro','Co-founded an ice cream business with my family, making','Built an ice cream shop from the ground up with my family, making')
edit('src/pages/resume.astro','My brother and I oversaw daily operations.','My brother and I oversaw daily operations, running the business for a couple of years before it closed in 2023.')
edit('src/pages/index.astro','number={i+1}/>)}</div></section>','number={i+1}/>)}</div><div style="display:flex;justify-content:flex-end;margin-top:26px"><a class="text-link" href="/projects/">All projects <span aria-hidden="true">↗</span></a></div></section>')
edit('src/data/projectMedia.ts'," {image:aeroAirfoilStream,alt:'Source-panel streamlines around a symmetric NACA 0017 airfoil.',caption:'Study 2: NACA 0017 streamlines at zero angle of attack.',fit:'contain'}]}",']}' )
edit('src/data/experience.ts',"company:'HiveTech AI',","company:'HiveTech AI',url:'https://www.linkedin.com/company/hivetech-ai/posts/?feedView=all',")
edit('src/data/experience.ts',"company:'Diagnostic Devices Inc. (DDI)',","company:'Diagnostic Devices Inc. (DDI)',url:'https://www.linkedin.com/company/diagnostic-devices-inc/',")
edit('src/data/experience.ts',"company:'University of Hartford Makerspace',","company:'University of Hartford Makerspace',url:undefined,")
edit('src/pages/resume.astro','<h3>{item.company}</h3>','<h3>{item.url ? <a href={item.url} target="_blank" rel="noopener noreferrer">{item.company} ↗</a> : item.company}</h3>')
edit('src/pages/about.astro','<p class="eyebrow">{item.company}</p>','<p class="eyebrow">{item.url ? <a href={item.url} target="_blank" rel="noopener noreferrer">{item.company} ↗</a> : item.company}</p>')
edit('src/pages/about.astro','I also served as founding president of the University of Hartford Kappa Sigma chapter. Building a new organization meant developing recruitment and organizational processes, leading events, and supporting philanthropic initiatives.','As founding president, I built the University of Hartford Kappa Sigma organization from nothing alongside two of my best friends. We developed recruitment and organizational processes, led events, and supported philanthropy. Earning our charter in January 2026 cemented the chapter’s status and made that shared effort a lasting part of the university.')
edit('src/pages/about.astro','Before university, I co-founded Scruton Brothers Ice Cream, an allergy-friendly business in Southern Pines, North Carolina. Equipment problems and supply logistics gave me early experience with solving practical problems while keeping an operation running.','Before university, my family and I built Scruton Brother’s Ice Cream from the ground up in Southern Pines, North Carolina. My brother and I ran daily operations for a couple of years before it closed in 2023. My own food allergies helped shape our dairy-free and gluten-free options; equipment problems and supply logistics taught me how to keep a business running. <a href="https://www.instagram.com/scrutonbrothersicecream/" target="_blank" rel="noopener noreferrer">See our family business on Instagram ↗</a>')
edit('src/content/projects/2025-08-12-pcb-demo.md','## Signal path and design choices','## From PSpice verification to EasyEDA layout\nI verified the circuit’s modeled behavior in PSpice through AC sweeps, transient analysis, FFTs, and load comparisons. These checks examined gain, filtering, bias, and clipping under the study’s simulated input conditions.\n\nI then translated the circuit into a single-layer PCB design in EasyEDA. The render showcased on this page is that board layout, connecting the simulation work to a proposed physical implementation. The PCB was designed digitally; fabrication and bench verification remain future work.\n\n## Signal path and design choices')
